### ISSUE TITLE
Passing in list of database names to create in cluster does not work as expected

### ISSUE THREAD

**Issue by JohnDzialo** [mohsenSy/terraform-digitalocean-db#1]
I see in your example for postgres you have a databases variable. A list of strings is passed in to the module to create a database for each item in the list.  This is not implemented anywhere. 

The example that references this variable is [here](https://registry.terraform.io/modules/mohsenSy/db/digitalocean/latest)

I am happy to make a PR if you like, just curious if this was a future feature that has not been added in the master branch yet.

Thanks!

**Comment by JohnDzialo** [comment]
@mohsenSy I have a branch that fixes a few bugs.  Would be happy to make a PR if you allow my user to contribute.

**Comment by mohsenSy** [comment]
@JohnDzialo thanks a lot for your contributions, in order to merge them you must create fork my repository and create a PR from your repository to mine and then I can accept it. I am looking forward to see your PR

**Comment by JohnDzialo** [comment]
https://github.com/mohsenSy/terraform-digitalocean-db/pull/2

**Comment by mohsenSy** [comment]
Closed by #2 thanks @JohnDzialo
